name: 주제 선정하기
description: 학습 주제 선정을 위한 이슈 생성을 합니다.
title: "[YY/MM/DD]: "
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > 
        > ### 주제 선정 전 확인사항
        >
        > - 동일한 주제가 이미 작성되어 있는지 확인해주세요. 
        >   - 동일한 주제가 이미 작성된 경우 기존 내용을 확인하고 부족한 부분이 있다면 수정 PR을 작성해주세요!

        <br/>

  - type: dropdown
    attributes:
      label: "카테고리"
      description: "콘텐츠 카테고리를 선택해주세요. 기타를 선택하고 새로운 카테고리가 추가되었다면 이후 이슈 템플릿 수정 부탁드립니다."
      options:
        - "CS"
        - "프로그래밍"
        - "프론트엔드"
        - "자바스크립트"
        - "리액트"
        - "기타"
    validations:
      required: true

  - type: input
    attributes:
      label: "제목"
      description: "내용을 간단하게 설명할 수 있는 제목을 작성해주세요"
      placeholder: "제목을 입력해주세요"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "내용 구성"
      description: "어떤 식으로 학습을 진행할지 궁금한 내용이나 간략한 구성을 작성해주세요"
      placeholder: "내용 구성을 간략하게 작성해주세요"
    validations:
      required: true
